apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mediawiki
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediawiki
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
    - type: Resource
      resource:
         name: memory
         targetAverageUtilization: 50  
