apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:<>
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https 
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60" 
    #service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-XXXX"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=dev,owner=devops"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5" 
  labels:
    app: mediawiki

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mediawiki


